version: '3.8'

services:
  db:
    image: postgres:17
    container_name: todo_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - PORT=8080
    restart: always

volumes:
  pgdata:
